version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pharma_go_api
    ports:
      - "5432:5432"
    
  backend:
    build: .
    environment:
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@db:5432/pharma_go_api"
    ports:
      - "8080:8080"
    depends_on:
      - db
