name: CI/CD

on:
  push:
    branches: [ "main" ] # Sur push main => déploiement Staging
    tags: [ "v*" ] # Sur tag v* => déploiement Prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run Tests
      env:
        FRONT_BASE_URL: ${{ secrets.FRONT_BASE_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ENVIRONMENT: "staging"
      run: |
        source env/bin/activate
        pytest --maxfail=5 --disable-warnings

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker with GCP Artifact Registry
      run: |
        gcloud auth configure-docker europe-west9-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadataapi/pharmadataapi:$GITHUB_SHA .
    - name: Push Docker image
      run: |
        docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadataapi/pharmadataapi:$GITHUB_SHA

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/main'
      run: |
        gcloud run deploy api-staging \
          --image europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadataapi/pharmadataapi:$GITHUB_SHA \
          --platform managed \
          --region europe-west9 \
          --allow-unauthenticated \
          --set-env-vars ENVIRONMENT=staging \
          --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --set-env-vars FRONT_BASE_URL=${{ secrets.FRONT_BASE_URL }}

    - name: Deploy to Prod
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        gcloud run deploy api-prod \
          --image europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/pharmadataapi/pharmadataapi:$GITHUB_SHA \
          --platform managed \
          --region europe-west9 \
          --allow-unauthenticated
